### ISSUE TITLE
util is not defined

### ISSUE THREAD

**Issue by scottie** [khoazero123/node-gdrive#2]
The issue is util is not defined in 
`
ReferenceError: util is not defined
    at Download.<anonymous> (/home/scott/work/backtest-data-downloader/node_modules/node-gdrive/lib/download.js:96:13)
    at invokeFunc (/home/scott/work/backtest-data-downloader/node_modules/lodash/lodash.js:10333:23)
    at leadingEdge (/home/scott/work/backtest-data-downloader/node_modules/lodash/lodash.js:10343:26)
    at Download.debounced [as handlePrintProgress] (/home/scott/work/backtest-data-downloader/node_modules/lodash/lodash.js:10410:20)
    at PassThrough.<anonymous> (/home/scott/work/backtest-data-downloader/node_modules/node-gdrive/lib/download.js:121:20)
`

Fix:
Add this line to top of download.js
`const util = require("./util");`

Pull request with fix initiated.

**Comment by scottie** [comment]
https://github.com/khoazero123/node-gdrive/pull/3
